# Generated by Django 5.1.7 on 2025-03-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='line_items',
            field=models.JSONField(default=dict, verbose_name='Line Items'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal Amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tax Amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vendor_details',
            field=models.TextField(verbose_name='Vendor Details'),
        ),
    ]
