# Generated by Django 5.1.7 on 2025-03-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_invoice_created_at_alter_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=100, verbose_name='Invoice Number'),
        ),
        migrations.AlterField(
            model_name='invoicedata',
            name='extracted_data',
            field=models.TextField(),
        ),
    ]
